name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Run tests
      run: npm test || true
      
    - name: Generate deployment package
      run: |
        zip -r eb-node-app.zip * .ebextensions -x "node_modules/*" "*.git*"
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Upload to S3
      run: |
        aws s3 cp eb-node-app.zip s3://week3nodeapp/eb-node-app.zip-${{ github.sha }}.zip
